server:
  port: ${SERVER_PORT:8081}
spring:
  graphql:
    graphiql:
      enabled: ${GRAPHIQL_ENABLED:false}
  datasource:
    url: jdbc:h2:./.local-db/customers
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
application:
  initialization:
    enabled: true
